apiVersion: v1
kind: Pod
metadata:
  name: live-config-pod
spec:
  containers:
    - name: live-config-pod-ctr
      image: busybox     #nginx doesnot support shell commands thats why busybox will work here
      command:
        - sh
        - -c
        - |
          while true; do
            echo "===== Reading Message: Hello====="
            cat /etc/config/message
            echo "==========================="
            sleep 5
          done

      volumeMounts:
        - name: config-volume
          mountPath: /etc/config #this is the path where configMap is mounted 

  volumes:
    - name: config-volume
      configMap:
        name: live-configmap