apiVersion: v1
kind: Pod
metadata: 
  name: dynamic-pod
spec:
  containers: 
    - name: dynamic-pod-ctr
      image: busybox:1.26
      command: [
         "sh",
         "-c",
         echo "Hello world" > /data/my-msg.txt && sleep 3600
      ]  
      volumeMounts:
        - name: dynamic-vol
          mountPath: /data
  volumes:
    - name: dynamic-vol
      persistentVolumeClaim:
         claimName: dynamic-pvc        