apiVersion: v1
kind: Pod
metadata:
   name: test-pod
spec:
   containers:
     - name: busybox-ctr
       image: busybox:1.26
       command: [
          "sh",
          "-c",
          echo "timestamp $(date)" > /data/message.txt  && sleep 3600
        ]   
       volumeMounts:
          - name: empty-dir
            mountPath: /data

   volumes:
     - name: empty-dir
       emptyDir: {}          
            