apiVersion: v1
kind: Pod
metadata:
   name: pv-pod
spec: 
  containers:
   -  name: busy-box
      image: busybox:1.26
      command: ["/bin/sh","-c","echo \"Pod started at $(date)\" >> /data/message.txt; sleep 3600"]   

      volumeMounts:
        - name: pvc-storage
          mountPath: /data
  volumes:
  - name: pvc-storage
    persistentVolumeClaim:
     claimName: test-pvc
        
