apiVersion: v1
kind: PersistentVolume
metadata:
   name: pod-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
      - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "manual" 
  hostPath:
     path: /tmp/k8s-pv-data


