# Stage 1: Build 
FROM eclipse-temurin:21 AS builder

WORKDIR /app

COPY HelloWorld.java .

RUN javac HelloWorld.java

# Stage 2: Runtime
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app



COPY --from=builder  /app/HelloWorld.class .



EXPOSE 8080
CMD ["java", "HelloWorld"]

