apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache-dep
spec:
   replicas: 1
   selector: 
     matchLabels:
       app: php-apache
   template:
      metadata:
        labels:
          app: php-apache
      spec:
         containers:
           - name: php-apache-ctr
             image: registry.k8s.io/hpa-example
             ports:
               - containerPort: 80
             resources:
               requests:
                 cpu: 200m           
                 