[application:children]
web
app

[all_servers:children]
application
db


[web]
web-server-ubuntu ansible_host=16.147.245.34 ansible_user=ubuntu 

[app]
app-server-redhat ansible_host=54.189.66.22  ansible_user=ec2-user

[db]
db-server-amazon-linux ansible_host=52.38.102.66  ansible_user=ec2-user

#web-server-ubuntu ansible_user=ubuntu
#app-server-redhat ansible_user=ec2-user
#db-server-amazon-linux ansible_user=ec2-user

[all:vars]
#ansible_user=ubuntu
#ansible_user=ec2-user
#ansible_user=ec2-user
ansible_ssh_private_key_file=~/ansible-master-key
ansible_python_interpreter=/usr/bin/python3
ansible_host_key_checking=false 