[all:vars]
ansible_ssh_private_key_file=/home/ubuntu/ansible/keys/observability_key_pair
ansible_python_interpreter=/usr/bin/python3
ansible_host_key_checking=false

[servers]
observability_instance ansible_host=54.70.105.40 ansible_user=ubuntu
