apiVersion: v1
kind: Pod
metadata: 
   name: pending-pod
spec: 
  containers: 
     - name: pending-pod-ctr
       image: nginx
       resources:
          requests:
            cpu: "100m" 
            memory: 128Gi
               