apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
spec:
  containers:
    - name: nginx-ctr
      image: nginx:1.26
      resources:
        requests:
          cpu: "100m"
          memory: "120Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"